//parties de routes - garder le texte sans espaces
export const PolitiqueConfidentialite_route = "PolitiqueConfidentialite"
export const MentionsLegales_route = "MentionsLegales"
export const Parametres_route = "Parametres"
export const Mespatients_route = "Mespatients"
export const MonSite_route = "MonSite"
export const GererFactures_route = "GererFactures"
export const ProchaineVisio_route = "ProchaineVisio"
export const AdminDashboard_route = "AdminDashboard"
export const statistics_route = "statistics"
export const notifications_route = "notifications"
export const admin_route = "admin"
export const users_route = "users"
export const inscriptions_route = "inscriptions"
export const appointments_route = "appointments"
export const echelles_route = "echelles"
export const factures_route = "factures"