export const ToutDroitsReserves = "© 2021 Appsy - Tout droits réservés"
export const MentionsLegales = "Mentions légales"
export const PrivacyPolicy = "Politique de confidentialité"
export const TexteFooterPatient = "AppTCC est un ensemble d’outils que nous mettons à votre disposition pour améliorer votre vie quotidienne."
export const TexteFooterTherapeute = "AppTCC est un ensemble d’outils permettant d’améliorer votre visibilité, faciliter la gestion de vos rendez-vous, optimiser votre temps."
export const Contact = "Contact"
export const PlusInfoSur = "Plus d’infos sur : "


export const SeDeconnecter = "Se déconnecter"
export const Messagerie = "Messagerie"
export const MonProfil = "Mon profil"
export const CreerAccesPatient = "Créer un accés patient"


// Create access patient use 
export const EmailPatient = "Email de patient"
export const TelephonePatient = "Téléphone de patient"
export const Telephone = "Téléphone"
export const Nom = "Nom"
export const Prenom = "Prénom"

export const Valider = "Valider"

export const TelechargerGuide = "Télécharger le guide"


// générale : 
export const Agenda = "Agenda";
export const Adresse = "Adresse";
export const DateInscription = "Date d'inscription"

// Text button: 
export const AjouterChamp = "Ajouter un champ"
export const AjouterAnalyse = "Ajouter une analyse"
export const AjouterCercleVicieux = "Ajouter un cercle vicieux"
export const AjouterDocument = "Ajouter un document"
export const UploaderDocument = "Upload le document"
export const OutilsTcc = "Outils TCC"
export const SuivieIntro = "Activez ou désactivez les outils à l’aide du cadenas afin que votre patient puisse les retrouver sur son application AppTCC."

// Filtre
export const FILTRER_SITUATION = "FILTRER LES SITUATIONS :"
export const FILTRER_TACHE= 'FILTRER LES TÂCHES :'

// Exercice exposition
export const ANXIETE_AVANT = "ANXIÉTÉ AU DÉPART"
export const ANXIETE_APRES = "ANXIÉTÉ ACTUELLE"
export const FUTUR = "FUTUR"
export const DESENSIBILISE = "DESENSIBILISE"
export const EXPOSITION = "EXPOSITION"
export const NOMBRE_EXPOSITION = "Nombre d’exposition :"
export const EXPOSITION_A_REALISER_TEXT = "Expositions à réaliser"
export const DESENSIBILISE_TEXT = "Désensibilisées"
export const FUTUR_TEXT = "Futures"

// Text Exercices:
export const SANS_TEXT = 'Sans objectif de temps ni de réduction d’angoisse'
export const MOITIE_TEXT = 'Je souhaite m’exposer jusqu’à ce que mon angoisse ait diminué de moitié'
export const DISPARU_TEXT = 'Jusqu’à ce que mon angoisse ait disparu'
export const DUREE_TEXT = 'Je souhaite m’exposer pendant une durée précise'
export const OBJECTIF_TEXT = 'Définir l’objectif soi-même'

export const SANS_REF = 'SANS'
export const MOITIE_REF = 'MOITIE'
export const DISPARU_REF = 'DISPARU'
export const DUREE_REF = 'DUREE'
export const OBJECTIF_REF = 'OBJECTIF'

export const DESENSIBILISE_REF = "desensibilise"
export const EXPOSITION_REF = "exposition"
export const FUTUR_REF = "Futures"
export const AREALISER_REF = "Arealiser"
export const ACQUISE_REF = "Acquises"

// Exercice Activation Comportementale
export const TACHE_A_REALISER_TEXT = "Tâches à réaliser"
export const TACHE_FUTUR_TEXT = "Tâches futures"
export const TACHE_ACQUISES_TEXT = "Tâches acquises"


export const AREALISER = "A réaliser"
export const ACQUISE = "Acquises"

export const DIFFICULTE = "DIFFICULTÉ"
export const PLAISIR = "PLAISIR"
export const EXPOSITION_DUMMY_EXAMPLE = "Peur de sauter d’un pont"

export const EMPTY_EXERICE_ACTIVATION = "Aucun exercice d'exposition d'activation comportementale trouvé."
export const EMPTY_EXERICE_EXPOSITION= "Aucune exercice d'exposition trouvé."
export const JE_SOUHAITE_TEXT= "Je souhaite que mon patient réussisse à :"
export const NIVEAU_DIFFICULTE_TEXT= "Niveau de difficulté à l’idée de réaliser la tâche :"
export const NIVEAU_SATISFACTION_TEXT= "Niveau de satisfaction à l’idée d’avoir réalisé la tâche :"
export const NIVEAU_PLAISIR_TEXT="Niveau de plaisir à l’idée de réaliser la tâche :"
export const VOULEZ_VOUS_PLANIFIER_TEXT="Voulez-vous planifier l’exercice ?"
export const PLANIFIER_CHAQUE_JOUR_TEXT="Planifier tour les jours"
export const OUI="Oui"
export const NON="Non"
export const TYPE_TACHE_TEXT="Type de tâche :"

// titres add situation: 
export const QUELLE_PENSEE = 'Quelle pensée est associé à cette émotion ?'
export const PENSEE = "Pensée"


// Notifications 
export const Aujourdhui ="Aujourd'hui"
export const MarquerCommeVu ="Marquer comme vu"
export const Notifications ="Notifications"

// limit access page 
export const AccesBloque = "Accès bloqué"
export const EssaiExpire = "Période d’essai expirée"
export const ModifierMonOffre = "Modifier mon offre"
export const ContacterEquipe = "Contacter l’équipe"
export const CommencerPeriodeEssai = "Commencer une période d’essai de 30 jours"

export const AbonnementLimiteChangeAbonnementContactEquipe = "Votre abonnement ne vous permet pas d’accéder à cet outil. Vous pouvez changer d’abonnement sur notre site Appsy.fr ou contacter notre équipe."
export const ExpireEssaiContinuerUtiliseOutils = "Votre période d’essai de 30 jours a expirée. Pour continuer d’utiliser les outils, vous pouvez modifier votre abonnement sur notre site Appsy.fr ou contacter notre équipe."


// MonSite page 
export const TextePlaceholderTitre = "Titre à afficher sur mon site."	
export const Periode = "Période"	
export const Diplomes = "Diplômes nationaux et universitaires :"	
export const MonParcours = "Mon parcours :"	
export const Quisuisje = "Qui suis-je ?"	
export const Titre = "Titre"
export const MonSiteProfile = "Mon Site"	
export const TextePlaceholderQuisuisje = "Description du psychologue"	
export const Experience = "Experience"	
export const Intitule = "Intitulé"	
export const ModifierImg = "Modifier la photo"
export const Consultations = "Consultations"	
export const TextePlaceholderConsulations = "Description des consultations que je propose."	
export const ApprocheTherapeutique = "Mon approche thérapeutique :"	
export const TherapieComportemental = "Titre de l'approche"	
export const TextePlaceholderTherapieComp = "Description de l'approche"	
export const Galerie = "Galerie"	
export const Tarifs = "Tarifs"	
export const Image_cabinet = "Image cabinet"	
export const TextePlaceholderCarteNonAcc = "Carte vitale non acceptée"	
export const Prix = "Prix"	
export const HorairesOuvertures = "Horaires d’ouvertures"	
export const InformationsPratiques = "Informations pratiques"	
export const ParkingPublic = "Parking public"	
export const MoyensTransports = "Moyens de transports"	
export const Horaire = "Horaire"	
export const Acces = "Accès"	
export const Retour = "Retour"
export const Cabinet = "Cabinet"
export const CheckAvailability = "Vérifier la disponibilité"	
export const UrlDuSiteTitle = "Nom de mon site"	
export const siteUrlPlaceholder = "votre-choix"	
export const MettreAJourSite = "Mettre à jour mon site"	
export const siteUrlPrefixVercel = "https://apptcc.vercel.app/"	
export const VisiterMonSite = "Visiter mon site"	
export const Photo_consultations = "Photo de consultations"	
export const lienDemoMonSite = "https://www.youtube.com/watch?v=cCoV_UU80yc";	

// Profile
export const Modification_bien_saisie = "Modification bien saisie"
export const RenseignerLienFiche = "Veuillez renseigner le lien de votre fiche (site appsy)"	
export const Veuillez_saisir_votre_adresse = "Veuillez saisir votre adresse"
export const Veuillez_saisir_votre_ville = "Veuillez saisir votre ville"
export const Veuillez_saisir_votre_codepostal = "Veuillez saisir votre code postal"
export const CodePostal_invalide = "Code Postal invalide"
export const Photo_profile = "Photo de profile"
export const Mon = "Mon"
export const Erreur_chargement_notifications_derniers_acts = "Erreur lors le chargement des notifications de derniers activités"







export const AccederFiche = " Accéder à sa fiche"
export const BienaVous = "Bien à vous,"
export const ChangerParAutrePsychologue = "Vous souhaitez être suivi par un autre psychologue ?"
export const Changerpsychologue = "Changer de psychologue"
export const EmailAddress = "Email"
export const Enregistrer = "Enregistrer"
export const EquipeAppsy = "L’équipe Appsy"
export const FirstName = "Prénom"
export const NousContacterDemanderChangement = "Nous vous invitons à nous contacter afin que nous puissions répondre à votre demande :"
export const NumeroTelephone = "Numéro de téléphone"
export const PostalCode = "Code postal"
export const Psychologue = "Psychologue"
export const SuppresionCompte = "Supprimer mon compte"
export const SuppresionTexte = "Vous avez la possibilité de supprimer votre compte AppTCC et les donnéesassociées. Cette action n’aura pas automatiquement pour effet de supprimer vos données personnelles des bases de données des professionnels de santé avec lesquels vous avez pris rendez-vous et/ou que vous avez consultés. Les professionnels de santé peuvent avoir un intérêt légitime à les conserver. Vous avez alors la possibilité d’exercer vos droits d’accès, de rectification ou de suppression directement auprès de ces derniers."
export const SuppresionTitre = "Suppression de votre compte AppTCC"
export const Supprimer = "Supprimer"
export const URLSITEPSY = "URL site internet ou fiche appsy"
export const Ville = "Ville"
export const VousSouhaitezSupprimerCompte = "Vous souhaitez supprimer définitivement votre compte ?"
export const ListeDesSituations = "Liste des situations"
export const AjouterUneSituation = "Ajouter une situation"
export const VoulezVousAjouterEchelle = "Voulez-vous ajouter une échelle ?"
export const TitreColonne = "Titre de la colonne :"
export const IntituleEchelle = "Intitulé de l’échelle"
export const Echelle = "Echelle"
export const Pourcentage = "Pourcentage"
export const Annuler = "Annuler"
export const AucuneMomentAgréable = "Aucun moment agréable trouvé pour ce patient"
export const  AucuneSituationTrouve = "Aucune situation trouvée pour ce patient"
export const  AjouterPensee = "Ajouter une pensée"
export const  AjouterDistortion = "Ajouter une distorsion"
export const  DescriptionDistortion = "Il s’agit d’erreurs de logique qui biaisent notre attention, notre perception et notre interprétation des évènements. Elles agissent comme des filtres, à travers lesquels nous voyons la réalité de façon déformée et négative."
export const  CroyancePensee = "Croyance en pensée :"
export const  Intensite = "Intensité :"
export const  Reevaluation = "Réevaluation :"
export const  PenseesAlternatives = "Pensées alternatives"
export const  DistorsionsCognitives = "Distorsions cognitives"
export const  SensationsPhysiques = "Sensations physiques"
export const  NouveauComportement = "Nouveau comportement"
export const  ComportementAdopteEmotion = "Comportement adopté en réaction à l’émotion"
export const  AutresPensees = "Autres pensées"
export const  ConsequencesNegatives = "Conséquences négatives"
export const  ConsequencesPositives = "Conséquences positives"
export const  SaisissezDateMomentAgreable = "Saisissez la date du moment agréable :"
export const  DEGRE_ANGOISSE_IDEE_EXP = "Degré de l’angoisse à l’idée de s’exposer :"
export const  ListeMomentsAgreables = "Liste des moments agréables"
export const  AjouterMomentAgreable = "Ajouter un moment agréable"
export const  IntensiteEmotion = "Intensité de l’émotion :"
export const AUCUNE_ANAMNESE_TROUVE = "Aucune anamnèse trouvée"
export const AUCUN_DOCUMENT_TROUVE = "Aucun document trouvé"
export const AUCUN_ANALYSE_TROUVE = "Aucune analyse trouvée"
export const AUCUN_CERCLE_TROUVE = "Aucun cercle vicieux trouvé"
export const AUCUN_NOTE_TROUVE = "Aucune note trouvée"
export const AUCUN_DOC_TROUVE = "Aucun document trouvé"
export const Charger = "Charger"
export const televerser = "Téléverser"
export const ConfirmerSuppression = "Confirmez vous la suppression ?"
export const QUELS_COMPORTEMENT_ADAPTE = "Quel(s) comportement(s) plus adapté(s) ai-je mis en place dans celle situation ?"
export const QUELS_COMPORTEMENT_DANS_SIT = "Quel(s) sont mes comportements dans cette situation ?"
export const JE_POURRAIS_DIRE_PERCEVOIR = "Ce que je pourrais plutôt me dire / percevoir"
export const QUELLES_SONT_DISTORSIONS = "Quelle(s) sont mes distorsions cognitives ?"
export const DEGRE_CROYANCE_PENSEE = "Degré de croyance en la pensée"
export const PENSEES_AUTOMATIQUES = "Pensées automatiques"
export const CE_QUE_JAI_RESSENTI = "Ce que j'ai ressenti dans mon corps"
export const INTENSITE_EMOTION_APRES = "Intensité de l’émotion après réévaluation"
export const SAISISSEZ_EMOTION_RESSENTIE = "Saisissez la ou les émotion(s) ressentie(s)"
export const SAISISSEZ_DATE_SITUATION = "Saisissez la date de la situation"
export const SITUATION_DECLANCHANTE = "Situation déclenchante"
export const SITUATION_QUI_A_DECLANCHE = "La situation qui a déclenché les émotions / pensées / comportements problématiques"

export const AutresPlaceholder = "Autres"
export const uneDistortionCognitive = "une distorsion cognitive :"
export const Afficher = "Afficher"
export const DixDernier = "Les 10 dernières"
export const Toutes = "Toutes"
export const EvalPlaisirDifficulte = "Évolution du plaisir et de la difficulté ressentie"
export const EvalAnxieteMax = "Évolution de l'anxiété maximale"
export const AnxieteMax = "Anxiété maximale"
export const Niveau = "Niveau"
export const MonPatient = " Mon patient"
export const SonSuivi = " Son suivi"
export const SesEchelles = "Ses échelles"
export const MesEchelles = "Mes échelles"
export const MesOutils_Breadcrumb = "Mes outils"
export const EXERCICE_EXPOSITION = "Exercice d’exposition"
export const EXERCICES_EXPOSITION = "Exercices d’exposition"
export const EXERCICES_ACTIV_COMPORT = "Exercices d’activation comportementale"
export const MOMENTS_AGREABLES = "3 moments agréables"
export const ANALYSE_FONCT = "Analyse fonctionnelle"
export const ANALYSES_FONCTIONELLES = "Analyses fonctionelles"
export const CERCLE_VICIEUX = "Cercle vicieux"
export const COLONNE_BECK = "Colonnes de Beck"
export const GESTION_EMOTIONNELLE = "Gestion émotionnelle"
export const A_FAIRE = "À faire"
export const PRISE_DE_NOTES = "Prise de notes"
export const ANTICIPATION = "Anticipation"
export const SITUATION = "Situation"
export const EMOTION = "Emotion"
export const COGNITIONS = "Cognitions"
export const COMPORTEMENT = "Comportement"
export const CONSEQUENCES = "Conséquences"
export const OUTILS_TCC = "Outils TCC"
export const DOSSIER = "Dossier"
export const AjouterGrilleSECCA = "Ajouter une grille SECCA"
export const AjouterGrilleSORC = "Ajouter une grille SORC"
export const GRILLE_SECCA = "Grille SECCA"
export const GRILLE_SORC = "Grille SORC"
export const STIMULUS = "Stimulus"
export const ORGANISME = "Organisme"
export const REPONSE = "Réponse"
export const NouvelleAnalyse  = "Nouvelle analyse fonctionnelle"
export const AnalyseSupprimé  = "Analyse fonctionnelle supprimée"
export const AnalyseModifié  = "Analyse fonctionnelle modifiée"

export const Deconnexion = "Déconnexion"
export const Exercice_activation_comportementale = "Exercice d’activation comportementale"
export const Vous_allez_etre_redirige = "Vous allez être redirigé"
export const Exercice_activation_bien_ajoute = "Exercice d'activation comportementale bien ajouté."
export const Erreur_ajout_exercice_activation = "Erreur lors l'ajout de l'exercice d'activation comportementale"
export const Exercice_activation_bien_modifie = "Exercice d'activation comportementale bien modifié."
export const Erreur_modification_exercice_activation = "Erreur lors la modification de l'exercice d'activation comportementale."
export const Erreur_activation_bien_supprime = "Exercice d'activation comportementale bien supprimé."
export const Erreur_suppression_exercice_activation = "Erreur lors la suppression de l'exercice d'activation comportementale."
export const Exercice_exposition_bien_ajoute = "Exercice d'exposition bien ajouté."
export const Erreur_ajout_exercice_exposition = "Erreur lors l'ajout de l'exercice d'exposition"
export const Exercice_exposition_bien_modifie = "Exercice d'exposition bien modifié."
export const Erreur_modification_exercice_exposition = "Erreur lors la modification de l'exercice d'exposition."
export const Erreur_exposition_bien_supprime = "Exercice d'exposition bien supprimé."
export const Erreur_suppression_exercice_exposition = "Erreur lors la suppression de l'exercice d'exposition."
export const Moment_agreable_bien_ajoute = "Moment agréable bien ajouté."
export const Erreur_ajout_moment_agreable = "Erreur lors l'ajout du moment agréable"
export const Moment_agreable_bien_modifie = "Moment agréable bien modifié."
export const Erreur_modification_moment_agreable = "Erreur lors la modification du moment agréable"
export const Moment_bien_supprime = "Moment agréable bien supprimé."
export const Erreur_suppression_moment_agreable = "Erreur lors la suppression du moment agréable."
export const Situation_bien_ajoute = "La situation est bien supprimée"
export const Erreur_suppression_situation = "Erreur lors la suppression de situation."
export const Activations_colonnes = "Activations des colonnes"
export const Emotions = "Emotions"
export const Pensees = "Pensées"
export const Comportements = "Comportements"
export const Comportement = "Comportement"
export const Situations_patient = "Situations du patient"
export const Tabulation_deux_elements = "Tabulation deux éléments"
export const Du = "Du"
export const defaultCountry = "fr"
export const defaultCountryUppercase = "FR"
export const Indicatif_telephonique = "+33"
export const Bloquer = "Bloquer"
export const Effacer = "Effacer"
export const Erreur_chargment_nombre_situations_semaine = "Erreur lors le chargment de nombre de situations de la semaine"
export const Erreur_chargment_nombre_situations_deux_dern_semaines = "Erreur lors le chargment de nombre de situations de deux dernieres semaines"
export const Erreur_chargment_nombre_expositions_semaine = "Erreur lors le chargment de nombre de expositions de la semaine"
export const Erreur_chargment_nombre_expositions_deux_dern_semaines = "Erreur lors le chargment de nombre de expositions de deux dernieres semaines"
export const Liste_vos_patients = "La liste de vos patients"
export const Nombre_patients_rattaches = "Nombre de patients rattachés"
export const Chercher_patient_par_nom_prenom_email = "Chercher un patient par son nom, prénom ou son émail"
export const Erreur_chargment_liste_patients = "Erreur lors le chargment de liste des patients"
export const Erreur_chargment_page = "Erreur lors le chargment de la page."
export const Cmpte_utilisateur_bien_reactive = "Le compte de cet utilisateur est bien réactivé"
export const Erreur_deactivation_utilisateur = "Erreur lors la déactivation d'utilisateur."
export const Bloquer_utilisateur_empechera_connecter = "Bloquer ou débloquer un utilisateur lui empechera de connecter au plateform"
export const Vous_avez_desactiver_utilisateur = "Vous avez désactiver cet utilisateur, il n'aura plus accées à son compte apptcc"
export const Dimanche = "Dimanche"
export const Lundi = "Lundi"
export const Mardi = "Mardi"
export const Mercredi = "Mercredi"
export const Jeudi = "Jeudi"
export const Vendredi = "Vendredi"
export const Samedi = "Samedi"
export const Cette_semaine = "Cette semaine"
export const Semaine_derniere = "Semaine dernière"
export const Expositions_vos_patients = "Expositions de vos patients"
export const Utilisateur_enregistre = "Utilisateur enregistré"
export const Veuillez_renseigner_votre_nom = "Veuillez renseigner votre nom svp"
export const Veuillez_renseigner_votre_prenom = "Veuillez renseigner votre prénom svp"
export const Veuillez_renseigner_votre_telephone = "Veuillez renseigner votre numéro de téléphone svp"
export const Ce_nest_pas_telephone_valide = "Ce n'est pas un numéro de téléphone valide!"
export const Email_required = "Email is Required"
export const Verifier_informations_saisies_puis_reessayer = "Veuillez vérifier les informations saisies puis réessayer!"
export const Numero_telephone_invalide = "Numéro de téléphone invalide"
export const Numero_telephone_obligatoire = "Numéro de téléphone obligatoire"
export const Veuillez_respecter_format_courriel = "Veuillez respecter le format du courriel (example@domaine.fr)"
export const Patient_introuvable = "Patient introuvable"
export const Aucune_donnee_disponible = "Aucune donnée disponible"
export const Page = "Page"
export const Bonjour = "Bonjour"
export const Note_enregistree = "Note enregistrée"
export const Exposition = "Exposition"
export const Cercle_vicieux_bien_enregistre = "Cercle vicieux bien enregistré"
export const Vous_avez_deja_lancer_version_dessai = "Vous avez déja lancer une version d'éssai appsy, veuillez contacter le service client svp"
export const Dernieres_situations = "Dernières situations"
export const Dernieres_expositions = "Dernières expositions"
export const Erreur_enregistrement_modifications = "Erreur lors l'enregistrement des modifications"
export const Rechercher_patient = "Rechercher un patient"
export const Bienvenue_dans_votre_dashboard = "Bienvenue dans votre dashboard"
export const Erreur_chargement_page_patient = "Erreur lors le chargement de page de patient"
export const Erreur_enregistrement = "Erreur lors de l'enregistrement."
export const Analyse_fonctionnelle_enregistree = "Analyse fonctionnelle enregistrée"
export const Cercle_vicieux_enregistre = "Cercle vicieux enregistré"
export const Mes_emotions_et_sentiments = "Mes émotions et sentiments"
export const Mes_pensees_automatiques = "Mes pensées automatiques"
export const Mes_comportements = "Mes comportements"
export const Tapez_votre_consigne = "Tapez votre consigne ..."
export const Ajouter_texte_note = "Ajouter le texte d'une note."
export const Charger_anciens_messages = "MCharger les anciens messages"
export const Mes_consequences_concretes_et_relationnelles = "Mes conséquences concrètes et relationnelles"
export const Description = "Description"
export const minutes = "minutes"
export const Seulement = "Seulement"
export const Anamnese = "Anamnèse"
export const Objectifs = "Objectifs"
export const Resultats = "Résultats"
export const Date_et_heure = "Date et heure"
export const Lexposition_exo_exposition_bien_modifiee = "L'exposition de l'exercice d'exposition est bien modifiée ."
export const Erreur_recuperation_expositions = "Erreur dans la récuperation des expositions"
export const Erreur_modif_exposition_exo_activation_comportementale = "Erreur lors la modification de l'exposition de l'exercice d'activation comportementale."
export const Enregistrer_modification = "Enregistrer la modification"
export const Ajouter_une_planification = "Ajouter une planification"
export const Vous_devez_ajouter_au_moins_une_planification = "Vous devez ajouter au moins une planification 😅"
export const Tache_plaisante = "Tâche plaisante"
export const Tache_quotidienne = "Tâche quotidienne"
export const Degre_angoisse_idee_de_exposer = "Degré de l’angoisse à l’idée de s’exposer"
export const Documents_partages = "Documents partagés"
export const Document_telecharger_avec_succes = "Document télécharger avec succés !"
export const Erreur_insertion_document = "Erreur lors de l'insertion du document."
export const Demarrer_visio = "Démarrer la visio"
export const Vous_navez_pas_visio_programmee_avec_ce_patient = "Vous n'avez pas de visio-consultation programmée avec ce patient"
export const Afficher_moins = "Afficher moins"
export const Lire_la_suite = "Lire la suite"
export const Documents_de_suivi = "Documents de suivi"
export const Pendant_exercice = "Pendant l’exercice"
export const Erreur_modification_exposition_exercice_exposition = "Erreur lors la modification de l'exposition de l'exercice d'exposition."
export const Lexposition_exo_activation_comportementale_bien_modifiee  = "L'exposition de l'exercice d'activation comportementale est bien modifiée."
export const Selectionnez_un_fichier = "Séléctionnez un fichier s'il vous plait !"
export const Erreur_serveur_veuillez_actualiser = "Erreur de serveur, veuillez actualiser la page svp"
export const Partage_avec_votre_patient = "Partagé avec votre patient"
export const Non_partage_avec_votre_patient = "Non partagé avec votre patient"
export const Erreur_insertion_note = "Erreur lors de l'insertion de note."
export const a_accentgrave = "à"
export const Duree = "Durée"
export const Pas_de_durée = "Pas de durée"
export const Chronometre = "Chronométre"
export const Angoisse_avant = "Angoisse avant"
export const Angoisse_max = "Angoisse max"
export const Angoisse_finale = "Angoisse finale"
export const Pensees_anxiogenes = "Pensées anxiogènes"
export const Commentaire_TEXT = "Commentaire"
export const Plaisir = "Plaisir"
export const Satisfaction = "Satisfaction"
export const Difficulte = "Difficulté"
export const Aucun_exercice = "Aucun exercice"
export const d_exposition = "d'exposition"
export const d_activation = "d'activation"
export const Type_de_tache = "Type de tache"
export const Anxiete = "Anxiété"
export const Creation = "Création"
export const Modification = "Modification"
export const Sur_10 = "Sur 10"
export const Moment = "Moment"
export const Ajouter = "Ajouter"
export const title = "title"
export const Le = "Le"
export const Bien_etre = "Bien-être"
export const Nouveaux_comportements = "Nouveaux comportements"
export const Rendezvous_par_page = "Rendez-vous par page"
export const Saisissez_commentaire_de_ce_moment = "Saisissez un commentaire à propos de ce moment"
export const Notez_intensite_bienetre_ressenti = "Notez l’intensité du bien-être ressenti "
export const Decrivez_moment_agreable = "Décrivez le moment agréable"
export const Creer_situation_anxiogene = "Créer une situation anxiogène"
export const Liste_des_taches = "Liste des tâches"
export const Creer_une_tache = "Créer une tâche"
export const Aucun_moment_nest_sasie = "Aucun moment agréable n'est sasie pour le moment"
export const Veuillez_saisir_description_moment_agreable = "Veuillez saisir la description du moment agréable."
export const Situations_anxiogenes = "Situations anxiogènes"
export const dune_nouvelle_colonne_Beck = "d'une nouvelle colonne de Beck"
export const Peur_sauter_dun_pont = "Peur de sauter d’un pont"
export const nest_saisi_pour_le_moment = "n'est saisi pour le moment"
export const Le_niveau_du_plaisir_nombre_entre_0_10  = "Le niveau du plaisir doit être un nombre entre 0 et 10."
export const Le_niveau_du_satisfaction_nombre_entre_0_10  = "Le niveau du satisfaction doit être un nombre entre 0 et 10."
export const Le_niveau_de_bienetre_nombre_entre_0_10  = "Le niveau du bien-être doit être un nombre entre 0 et 10."
export const Le_niveau_du_difficulte_nombre_entre_0_10  = "Le niveau du difficulté doit être un nombre entre 0 et 10."
export const Langoisse_avant_nombre_entre_0_10  = "L'angoisse avant doit être un nombre entre 0 et 10."
export const Langoisse_maximale_nombre_entre_0_10  = "L'angoisse maximale doit être un nombre entre 0 et 10."
export const Langoisse_finale_nombre_entre_0_10  = "L'angoisse finale doit être un nombre entre 0 et 10."
export const Veuillez_remplir_champs_obligatoires = "Veuillez remplir tous les champs obligatoire SVP"
export const Situation_bien_enregistree = "La situation est bien enregistrée"
export const Sensation_s_physique_s = "Sensation(s) physique(s)"
export const Nouveau_s_comportement_s = "Nouveau(x) comportement(s)"
export const Precisez_dautres_pensees = "Précisez si vous avez d’autres pensées"
export const Modifier = "Modifier"
export const tarif = "tarif"
export const Erreur = "Erreur"
export const Demo = "Démo"
export const Votre_site = "Votre site"
export const Minimum_3_caracteres = "Minimum 3 caractères"
export const Carcteres_autorises_Lettres_Chiffres_Tiret = "Carctères autorisés : Lettres, Chiffres, Tiret '-'"
export const Mon_site_bien_enregistre = "Mon site bien enregistré"
export const Modifications_images_cabinet_prise_en_compte = "Modifications d'images de cabinet bien prise en compte"
export const Modification_image_bien_enregistre = "Modification d'image bien enregistré"
export const Nom_disponible_et_enregistre = "Nom disponible et enregistré"
export const Realisee_le = "Réalisée le"
export const Difficulte_ressentie = "Difficulté ressentie"
export const Plaisir_ressenti = "Plaisir ressenti"
export const La_divination = "La divination"
export const La_dramatisation = "La dramatisation"
export const La_telepathie = "La télépathie"
export const Letiquetage = "L’étiquetage"
export const La_focalisation_somatique = "La focalisation somatique"
export const Le_raisonnement_emotionnel = "Le raisonnement émotionnel"
export const La_disqualification_du_positif = "La disqualification du positif"
export const La_responsabilisation = "La responsabilisation"
export const Le_tout_ou_rien = "Le « tout ou rien »"
export const Les_exigences_dogmatiques = "Les exigences dogmatiques"
export const Nous_interpretons_situation_ambigue = "Nous interprétons une situation ambiguë de manière négative, alors qu’elle peut être interprétée de multiples autres façons."
export const La_conclusion_sans_preuve = "La conclusion sans preuve"
export const Nous_ne_percevons_et_ne_retenons = "Nous ne percevons et ne retenons que l’aspect négatif d’une situation."
export const Labstraction_selective = "L’abstraction sélective"
export const Nous_amplifions_consequences_negatives = "Nous amplifions les conséquences négatives d’un événement, en les anticipant comme catastrophiques."
export const Nous_anticipons_lissue_negative = "Nous anticipons l’issue négative d’une situation à venir, comme si c’était la plus probable."
export const La_surgeneralisation = "La surgénéralisation"
export const Nous_tirons_conclusions_ou_edictons_regles = "Nous tirons des conclusions ou édictons des règles générales à partir d’un évènement isolé ou ponctuel."
export const pas_dexpositions_a_afficher  = "Il n'y a pas d'expositions a afficher"
export const Nous_croyons_connaitre_ou_deviner_pensees = "Nous croyons connaître ou deviner les pensées et les intentions des autres, alors qu’en réalité nous n’en savons rien avec certitude !"
export const Nous_nous_imposons_arbitrairement_ou_imposons = "Nous nous imposons arbitrairement - ou imposons aux autres - des obligations ou des besoins absolus."
export const Nous_interpretons_evenements_comme_negatifs = "Nous interprétons les événements comme négatifs ou positifs, sans nuances intermédiaires : c’est noir ou blanc !"
export const Nous_nous_attribuons_exagerement_la_responsabilite = "Nous nous attribuons exagérément la responsabilité des choses ou du comportement des autres."
export const Nous_portons_des_jugements_definitifs = "Nous portons des jugements définitifs sur nous-même ou sur les autres, à partir d’un fait ponctuel"
export const Nous_minimisons_experience_positive_ou_nous_la_transformons = "Nous minimisons une expérience positive ou nous la transformons en expérience négative."
export const Nous_tirons_une_conclusion_sur_la_realite = "Nous tirons une conclusion sur la réalité à partir de notre état émotionnel, en considérant à tort nos sentiments comme des preuves."
export const Nous_interpretons_les_stimuli_internes = "Nous interprétons les stimuli internes de notre corps comme des indicateurs fiables d’un danger imminent pour notre santé ou notre survie."
export const search = "search..."
export const There_Are_no_result_found = "Opps!! There are no result found."
export const logo = "logo"
export const facebook_link = "https://www.facebook.com/apptccofficiel"
export const linkedin_link = "https://fr.linkedin.com/company/appsyfrance"
export const instagram_link = "https://www.instagram.com/apptcc_fr/"
export const youtube_link = "https://www.youtube.com/channel/UC1-QSO70um_mCMn11PJUVTQ"
export const nom_entreprise = "APPTCC"
export const Nouvelle_echelle = "Nouvelle échelle"
export const Echelle_recu = "Echelle reçu"
export const Echelle_passee = "Echelle passée"
export const Resultat_echelle = "Résultat d'échelle"
export const Nouveau_rendezvous = "Nouveau rendez-vous"
export const Rendezvous_modifie = "Rendez-vous modifié"
export const Rendezvous_supprime = "Rendez-vous supprimé"
export const Nouvelle_situation = "Nouvelle situation"
export const Situation_modifiee = "Situation modifiée"
export const Situation_supprime = "Situation supprimé"
export const Nouveau_exercice_activation = "Nouveau exercice d'activation"
export const Exercice_activation_modifie = "Exercice d'activation modifié"
export const Exercice_supprime = "Exercice supprimé"
export const Exercice_activation_realise = "Exercice d'activation réalisé"
export const Exercice_activation = "Exercice d'activation"
export const Nouveau_exercice_exposition = "Nouveau exercice d'exposition"
export const Exercice_exposition_modifie = "Exercice d'exposition modifié"
export const Exposition_supprime = "Exposition supprimé"
export const Exercice_exposition_realise = "Exercice d'exposition réalisé"
export const Nouveau_moment_agreable = "Nouveau moment agréable"
export const Moment_agreable_modifie = "Moment agréable modifié"
export const Moment_agreable_supprime = "Moment agréable supprimé"
export const Moment_agreable = "Moment agréable"
export const Facture = "Facture"
export const Factures = "Factures"
export const Paiement = "Paiement"
export const Paiement_recu = "Paiement reçu"
export const Facture_recu = "Facture reçu"
export const Nouveau_document = "Nouveau document"
export const Document_supprime = "Document supprimé"
export const Document = "Document"
export const General = "Général"
export const Echelles = "Echelles"
export const Therapeute = "Thérapeute"
export const Patient = "Patient"
export const Administrateur = "Administrateur"
export const Profil = "Profil"
export const Mes_rendezvous = "Mes rendez-vous"
export const Mes_outils_TCC = "Mes outils TCC"
export const Parametres = "Paramètres"
export const Mes_factures = "Mes factures"
export const Mes_patients = "Mes patients"
export const Les_echelles = "Les échelles"
export const Visioconsultation = "Visio-consultation"
export const Dashboard = "Dashboard"
export const Generer_une_facture = "Générer une facture"
export const Parametrer_mes_factures = "Paramétrer mes factures"
export const Utilisateur_introuvable = "Utilisateur introuvable"
export const Aucune_notification = "Aucune notification"
export const Admin_Dashboard = "Admin Dashboard"
export const Verifier_boite_mail = "Vérifier votre boite mail SVP!"
export const Verifier_votre_boite_mail_pour__resultats = "Vérifier votre boite mail SVP pour voir les résultats!"
export const Erreur_Notification_pas_ouverte = "Erreur: Notification ne peux pas être ouverte"
export const Erreur_changement_status_notifications = "Erreur: lors le changement de status des notifications"
export const Erreur_chargement_notifs_derniers_act = "Erreur lors le chargement des notifications de derniers activités"
export const contacter_votre_psychologue_pour_avoir_les_resultats = "Vous pouvez contacter votre psychologue pour avoir les résultats."
export const Statistiques = "Statistiques"
export const Connections = "Connections"
export const Inscriptions = "Inscriptions"
export const Rendezvous = "Rendez-vous"
export const Mes_echelles = "Mes_echelles"
export const janvier = "janvier"
export const fevrier = "février"
export const mars = "mars"
export const avril = "avril"
export const mai = "mai"
export const juin = "juin"
export const juillet = "juillet"
export const aout = "août"
export const septembre = "septembre"
export const octobre = "octobre"
export const novembre = "novembre"
export const decembre = "décembre"




export const ActivationDesExercices = "Activation des exercices :"
export const AjouterExercice = "Ajouter un exercice"
export const ListDesExercices = "Liste des exercices"

export const RelaxationTitle = "Relaxation"
export const LieuSurTitle = "Lieu sûr"
export const CoherenceCardiaqueTitle = "Cohérence cardiaque"
export const RespirationTitle = "Respiration"
export const MeditationTitle = "Meditation"

export const TypeDeLExerciceLabel = "Type de l’exercice :"
export const ChoisirUnTypeDExercicePlaceholder = "Choisir un type d'exercice"
export const TitreDeLexercice = "Titre de l’exercice :"
export const AjouterUnAudioExercice = "Ajouter un audio pendant l ‘exercice :"

export const ObjectifsExercice = "Objectifs de l’exercice :"
export const DefinissezObjectifsExercicePlaceholder = "Définissez l’objectif de l’exercice"

export const PlanificationTitle = "Planification :"
export const FoisParJourTitle = "Fois par jour"
export const LorsEtatAnxieuxTitle = "Lors d’un état anxieux"
export const AvantSituationAnxiogeneTitle = "Avant une situation anxiogène"
export const PendantSituationAnxiogeneTitle = "Pendant une situation anxiogène"
export const ApresSituationAnxiogeneTitle = "Après une situation anxiogène"
export const TousLesTitle = "Tous les :"
export const DefinissezQuandFaireExercicePlaceholder = "Définissez quand faire l’exercice"

export const ConsignesExercice = "Consignes de l’exercice :"
export const ConsignesExercicePlaceholder = "Inscrire les consignes afin d’expliquer l’exercice à votre patient."

export const NombreExpositionTitle = "Nombre d’expositions : "



export const DateEtHeure = "Date et heure"
export const StressTension = "Stress / tension "
export const Avant = "avant"
export const Apres = "après"
export const ElementsPerturbateursEventuels = "Elements perturbateurs éventuels"
export const Commentaire = "Commentaire"

export const SupprimerExerciceDefinitivement = "Supprimer l’exercice définitivement ?"

export const AjouterAudioAlExercice = "Ajouter un audio pendant l‘exercice :"
export const ImporterUnFichierAudio = "Importer un fichier audio"
export const ImporterUnNouveauFichier = "Importer un nouveau fichier"
export const SupprimerAudioDefenitivement = "Supprimer l’audio ?"

export const EnvoyerUnFichierAudio = "Envoyer un fichier audio"
export const conditionsChargmentNombreFichierMaximum = "Vous pouvez charger uniquement 10 fichiers maximum"
export const conditionsChargmentTailleFichierMaximum = "Chaque fichier ne doit pas dépasser 30 Mo"
export const AucunExerciceTrouve = "Aucun exercice trouvé"
export const EcouterUnAudioJusquaLaFin = "Ecouter un audio jusqu’à la fin"
export const SeRelaxerUnTempsImpartis = "Se relaxer pendant un temps impartis"

export const NouveauAlertNotificationTitle = "Alert"
export const urgent = "Urgent"
export const aucuneExposition = "Aucune exposition pour l'instant"

export const TempsInspirationText = "Temps d'inspiration"
export const tempsExpirationText = "Temps d'expiration"

export const tempsInspirationObligatoire = "Le temps d'inspiration et d'expiration est obligatoire pour ce type d'exercice";
export const titreExerciceObligatoire = "Le titre d'exercice est obligatoire"
export const TitreFichierAudio = "Titre de fichier audio"
export const Echec_enregistrement_exercice = "Echec d'enregistrement de l'exercice"
export const HEURES = "Heures"
export const MINUTES = "Minutes"
export const SECONDS = "Seconds"
export const CET_EXERCICE_EST_BIEN_SUPPRIME = "Cet exercice est bien suppimé"
export const ERREUR_SUPPRESION_EXERCICE = "erreur lors la suppresion de l'exercice"
export const ERREUR_MODIF_PARAMETERS = "erreur lors la modification des parameters"
export const ERREUR_CHARGEMENT_FICHIER_AUDIO = "Erreur lors le chargement de fichier audio"
export const AUDIO_ET_TITRE_OBLIGATOIRE = "Le fichier audio et le titre sont obligatoire"
